spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/github?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useSSL=false&serverTimezone=UTC
    username: root
    password: fml
    initial-size: 10
    max-wait: 10000
    maximum-pool-size: 100
    max-active: 100
    max-idle: 10
    minIdle: 2
    test-on-borrow: false
    test-on-return: true
    test-while-idle: true
    validation-query: select 1
    bindType: deviceType # 绑定的数据源类型

# 权限开关
authority:
  open: 0
# 是否使用数据权限
pms:
  needPmsControl: true

spring.redis:
    database: 0
    # host: 192.168.1.115
    host: localhost
    port: 6379
    password:
    timeout: 3000
    pool:
      max-active: 1024
      max-idle: 300
      max-wait: -1
      min-idle: 100